{{- if and .Values.grafanaExternalSecret.enabled }}
{{- $namespace := .Release.Namespace -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secrets
  namespace: {{ $namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore 
    name: {{ .Values.grafanaExternalSecret.secretStore }}
  target:
    creationPolicy: Owner
    name: grafana-external-secrets
  data:
  {{- with .Values.grafanaExternalSecret.secrets }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}