argocd:
  namespace: kube-system
  releaseName: aws-ebs-csi-driver

aws-ebs-csi-driver: 
  kubeNamespace: kube-system
  controller:
    serviceAccount:
      annotations: 
        eks.amazonaws.com/role-arn: arn:aws:iam::${ARGOCD_ENV_AWS_ACCOUNT}:role/eks/${ARGOCD_ENV_CLUSTER}/${ARGOCD_ENV_ENVIRONMENT}/eks-${ARGOCD_ENV_CLUSTER}-${ARGOCD_ENV_ENVIRONMENT}-AmazonEKS-CSI_Driver-role
  storageClasses:
    - name: gp3-retain
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
      parameters:
        type: "gp3"
  useOldCSIDriver: true
  customLabels:
    cluster: ${ARGOCD_ENV_CLUSTER}
    project: ${ARGOCD_ENV_CLUSTER}
    env: ${ARGOCD_ENV_ENVIRONMENT}
    tier: infra
    version: 2.13.0