{{ if .Values.clusterSecretStore.secretsManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  {{ if .Values.clusterSecretStore.secretsManager.nameSuffix }}
  name: aws-secretsmanager-{{ .Values.clusterSecretStore.secretsManager.nameSuffix }}
  {{ else }}
  name: aws-secretsmanager
  {{ end }}
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.secretsManager.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
{{ end }}
