apiVersion: v2
appVersion: 2.8.2
description: Helm chart for Grafana Loki in simple, scalable mode
name: loki-distributed
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
type: application
version: 0.70.0
dependencies:
- name: loki-distributed
  version: 0.70.0
  repository: https://grafana.github.io/helm-charts
