{{- if .Values.clusterIssuer }}
{{- range .Values.clusterIssuer }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
spec:
  {{- toYaml .spec | nindent 2}}
{{- end }}
{{- end }}
