argocd:
  namespace: cert-manager
  releaseName: cluster-issuer-aws
  externalHelmChartPath: "../"

clusterIssuer:
  letsencrypt-dns01:
    name: letsencrypt-dns01-${ARGOCD_ENV_DOMAIN}
    spec:
      acme:
        # You must replace this email address with your own.
        # Let's Encrypt will use this to contact you about expiring
        # certificates, and issues related to your account.
        email: ${ARGOCD_ENV_TECH_EMAIL}    # email to be communicated to ACME challenge
        # disableAccountKeyGeneration: false  # if true, reuse account if already exists on letsencrypt
        server: https://acme-v02.api.letsencrypt.org/directory
        preferredChain: "ISRG Root X1"   # new letsncrypt chain that supports wildcard certs
        privateKeySecretRef:
          # Secret resource used to store the account's private key.
          name: letsencrypt-dns01-${ARGOCD_ENV_DOMAIN}
        solvers:
        - dns01:
            route53:
              region: ap-southeast-1
              hostedZoneID: ${ARGOCD_ENV_HOSTED_ZONE_ID}
          selector:
            dnsZones:
              - ${ARGOCD_ENV_DOMAIN}