- alert: InstanceLowMemory
  expr: (1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100 > 85
  for: 10m
  labels:
    severity: critical
    alerts: common
    source: prometheus
    env: {{ .Values.environment }}
  annotations:
    summary: Instance out of memory
    description: "Node memory is filling up (< 10% left)"
    url: https://grafana.${ARGOCD_ENV_DOMAIN}/explore?orgId=1&left=%7B%22datasource%22:%22P1809F7CD0C75ACF3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P1809F7CD0C75ACF3%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%281%20-%20%28node_memory_MemAvailable_bytes%20%2F%20%28node_memory_MemTotal_bytes%29%29%29%2A%20100%20%3E%2085%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-5m%22,%22to%22:%22now%22%7D%7D