- alert: WorkerNodeNotReady
  annotations:
    description: "Worker node has been unready for more than 15 minutes."
    summary: Node is not ready.
  expr: kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0
  for: 15m
  labels:
    severity: warning
    alerts: common
    source: prometheus
    env: {{ .Values.environment }}