argocd:
  namespace: grafana-stack
  releaseName: grafana
  syncOptionReplace:
    - dashboard-geth-dashboard

grafana:
  nameOverride: grafana
  fullnameOverride: grafana
  kubeNamespace: grafana-stack

  # assertNoLeakedSecrets is a helper function defined in _helpers.tpl that checks if secret
  # values are not exposed in the rendered grafana.ini configmap. It is enabled by default.
  #
  # To pass values into grafana.ini without exposing them in a configmap, use variable expansion:
  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#variable-expansion
  #
  # Alternatively, if you wish to allow secret values to be exposed in the rendered grafana.ini configmap,
  # you can disable this check by setting assertNoLeakedSecrets to false.
  assertNoLeakedSecrets: false
    
  replicas: 1

  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "0.5"
      memory: 2Gi

  autoscaling:
    # TODO:
    # horizontal-pod-autoscaler  deployments/scale.apps "grafana" not found
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70

  datasources: 
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: prometheus
        type: prometheus
        url: http://thanos-query-frontend.prometheus-stack.svc:9090
        access: proxy
        isDefault: true
      - name: loki
        type: loki
        access: proxy
        url: http://loki-gateway
        jsonData:
          maxLines: 10000
          timeout: 600s
      - name: rds
        type: postgres
        url: ''
        user: ''
        secureJsonData:
          password: ''
        jsonData:
          database: ''
          sslmode: 'disable' # disable/require/verify-ca/verify-full
          maxOpenConns: 0 # Grafana v5.4+
          maxIdleConns: 2 # Grafana v5.4+
          connMaxLifetime: 14400 # Grafana v5.4+
          postgresVersion: 1400 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false
        # <bool> allow users to edit datasources from the UI.
        editable: true
  
  persistence:
    type: statefulset
    enabled: true
    storageClassName: gp3-retain

  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-http01
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.${ARGOCD_ENV_DOMAIN}

  admin:
    existingSecret: grafana-postgres-credentials
    userKey: postgres-user
    passwordKey: postgres-password


  initChownData:
    ## initChownData container image
    image:
      repository: busybox
      tag: "1.31.1"
    pullPolicy: IfNotPresent

  sidecar:
    image:
      repository: kiwigrid/k8s-sidecar
      tag: "1.19.2"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 150m
        memory: 50Mi
    dashboards:
      enabled: true
      searchNamespace: "grafana-stack"
      resource: configmap
      provider:
        updateIntervalSeconds: 10
        foldersFromFilesStructure: true
      defaultFolderName: null
      folderAnnotation: grafana_dashboard_folder
      
  rbac:
    namespaced: true

  grafana.ini:
    auth.basic:
      enabled: true
    auth.google:
      enabled: true
      client_id: $__file{/etc/secrets/google/client_id}
      client_secret: $__file{/etc/secrets/google/client_secret}
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allowed_domains: ${ARGOCD_ENV_AUTH_DOMAINS}
      allow_sign_up: true
      allow_assign_grafana_admin = true
      skip_org_role_sync = false
      role_attribute_path = email=='thanh.vo@ithacanoemon.tech' && 'GrafanaAdmin' || 'Editor'
    server:
      root_url: https://grafana.${ARGOCD_ENV_DOMAIN}
    users:
      auto_assign_org: true
      auto_assign_org_id: 1
      auto_assign_org_role: Editor
      editors_can_admin: true
    auth.anonymous:
      enabled: false
      org_name: Dashboard
      org_role: Viewer
      hide_version: false
    session:
      provider: file
      provider_config: sessions
      cookie_name: grafana_sess
      cookie_secure: false
      session_life_time: 86400
      gc_interval_time: 86400
    database:
      type: postgres
      host: postgresql:5432
      name: grafana
      user: grafana
      password: $__file{/etc/secrets/postgres/password}

  extraSecretMounts:
  - name: auth-google
    secretName: grafana-google-oauth-credentials
    defaultMode: 0440
    mountPath: /etc/secrets/google
    readOnly: true
  - name: auth-postgresql
    secretName: grafana-postgres-credentials
    defaultMode: 0440
    mountPath: /etc/secrets/postgres
    readOnly: true    

  podLabels:
    app: grafana
    cluster: ${ARGOCD_ENV_CLUSTER}
    project: ${ARGOCD_ENV_CLUSTER}
    env: ${ARGOCD_ENV_ENVIRONMENT}
    tier: infra
    version: 7.2.1

  useStatefulSet: true

  alerting:
    alert-group.yaml:
      file: alerting/alertGroup.yaml
    contact-points.yaml:
      file: alerting/contact-points.yaml

grafanaExternalSecret:
  enabled: false
  secretStore: secretstore
  secrets:
    - secretKey: admin-username
      remoteRef:
        key: /grafana/${ARGOCD_ENV_ENVIRONMENT}-${ARGOCD_ENV_CLUSTER}/admin/username
    - secretKey: admin-password
      remoteRef:
        key: /grafana/${ARGOCD_ENV_ENVIRONMENT}-${ARGOCD_ENV_CLUSTER}/admin/password

dashboardReloaderEnabled: false
# dashboardsToLoad: [] # directory name under dashboards
dashboardsToLoad: # only dashboards under these directories will be loaded into grafana 
  - infrastructure
  - ithacanoemon