# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
    - name: thanos
      image: docker.io/bitnami/thanos:0.32.5-debian-11-r1
apiVersion: v2
appVersion: 0.32.5
description: Thanos is a highly available metrics system that can be added on top of existing Prometheus deployments, providing a global query view across all Prometheus installations.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/thanos/img/thanos-stack-220x234.png
keywords:
- analytics
- monitoring
- prometheus
- thanos
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: thanos
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/thanos
version: 12.15.0
dependencies:
- name: thanos
  version: 12.15.0
  repository: https://charts.bitnami.com/bitnami
