argocd:
  namespace: prometheus-stack
  releaseName: kube-state-metrics
  
kube-state-metrics:
  nameOverride: kube-state-metrics
  fullnameOverride: kube-state-metrics
  kubeNamespace: prometheus-stack

  prometheus:
    monitor:
      enabled: true
      honorLabels: true
      additionalLabels: 
        prometheus: ${ARGOCD_ENV_CLUSTER}
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_cluster]
          action: replace
          targetLabel: cluster
        - sourceLabels: [__meta_kubernetes_pod_label_project]
          action: replace
          targetLabel: project
        - sourceLabels: [__meta_kubernetes_pod_label_env]
          action: replace
          targetLabel: env

  customLabels:
    cluster: ${ARGOCD_ENV_CLUSTER}
    project: ${ARGOCD_ENV_NAMESPACE}
    env: ${ARGOCD_ENV_ENVIRONMENT}
    tier: infra
    version: 5.15.2

  resources:
    limits:
      cpu: 100m
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 150Mi