- alert: PodNotReady
  annotations:
    description: 'Pod is either Pending/Unknown/Failed for 5 minutes already.'
    summary: Pod is not ready
    url: https://grafana.{{ .Values.grafanaDomain }}/explore?orgId=1&left=%7B"datasource":"P1809F7CD0C75ACF3","queries":%5B%7B"refId":"A","editorMode":"code","expr":"min_over_time%28sum%20by%20%28namespace,%20pod,%20cluster%29%20%28kube_pod_status_phase%7Bphase%3D~%5C"Pending%7CUnknown%7CFailed%5C"%7D%29%5B15m:1m%5D%29%20>%200","legendFormat":"__auto","range":true,"instant":true%7D%5D,"range":%7B"from":"now-1h","to":"now"%7D%7D
  expr: min_over_time(sum by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[15m:1m]) > 0
  for: 5m
  labels:
    severity: error
    alerts: common
    pods: notReady
    source: prometheus
    env: {{ .Values.environment }}