{
 "title": "Infrastructure Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "gryfyn,operator,htm" },
   {
    "name": "env",
    "query": {
     "query": "label_values(probe_success{}, env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Non-Running Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",phase!~\"(Running|Succeeded)\"} > 0)"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk( 1,(1 - ((avg_over_time(node_memory_MemFree_bytes{cluster=\"gryfyn\"}[10m]) + avg_over_time(node_memory_Cached_bytes{cluster=\"gryfyn\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"gryfyn\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{cluster=\"gryfyn\"}[10m]))))"
    }
   ]
  },
  {
   "title": "Pod Restart Total",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, pod) (kube_pod_container_status_restarts_total{cluster=~\"$cluster\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Running Pod (Phase)",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=~\"$cluster\",phase!~\"(Running|Succeeded)\"} > 0"
    }
   ]
  },
  { "title": "No Request Limit", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Bandwidth", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "ArgoCD Sync", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Cluster Capacity", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Storage %", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "API Latency", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Endpoints-$env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "env" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*zookeeper\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*kafka\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*redis\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*rds\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*keycloak\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*api-gateway\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*frontend\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*kms\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*ethereum-node\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\".*polygon-node\", env=~\"$env\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",cluster=\"$cluster\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingress/Certificate/Secret", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Certificate Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{cluster=~\"$cluster\"}) BY (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "External Secret Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (externalsecret_status_condition{cluster=~\"$cluster\", condition!=\"Deleted\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Certificate Expiration",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{cluster=~\"$cluster\"} - time()) BY (name,exported_namespace) )",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Log Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~\"$cluster\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", app!~\"zookeeper\" } |~ \"(?i)error\"",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Top 15 Log Publisher (Gryfyn app)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(15, count_over_time({cluster=~\"$cluster\"}[$__range]))"
    }
   ]
  }
 ]
}