{
 "title": "Amazon RDS - cloudwatch",
 "time": { "from": "2023-05-17T08:26:02.379Z", "to": "2023-05-17T09:08:26.005Z" },
 "panels": [
  {
   "title": "CPU utilization per instance [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{environment=\"develop\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database connections [count sum]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(dbinstance_identifier) (aws_rds_database_connections_maximum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available storage space [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(dbinstance_identifier) (aws_rds_free_storage_space_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available RAM [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(dbinstance_identifier) (aws_rds_freeable_memory_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read throughput [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(dbinstance_identifier) (aws_rds_read_throughput_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write throughput [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg by(dbinstance_identifier) (aws_rds_write_throughput_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read latency [sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by(dbinstance_identifier) (aws_rds_read_latency_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write latency [sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max by(dbinstance_identifier) (aws_rds_write_latency_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg by(dbinstance_identifier) (aws_rds_read_iops_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg by(dbinstance_identifier) (aws_rds_write_iops_sum)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}