{
 "title": "Hexsafe/Metazen Infrastructure Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "metazen" },
   { "name": "env", "query": "hexsafe,metazen" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Hexsafe/Metazen Infrastructure Overview</h1></center>"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Non-Running Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",phase!~\"Running|Succeeded\"})"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk( 1,100*(1 - ((avg_over_time(node_memory_MemFree_bytes{cluster=\"$cluster\"}[10m]) + avg_over_time(node_memory_Cached_bytes{cluster=\"$cluster\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"$cluster\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{cluster=\"$cluster\"}[10m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (node_filesystem_avail_bytes{job=\"node-exporter\",fstype!=\"\",cluster=\"$cluster\"}) / sum by (cluster) (node_filesystem_size_bytes{job=\"node-exporter\",fstype!=\"\",cluster=\"$cluster\"}) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", target=~\"$env.*\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",cluster=\"$cluster\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Not Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",cluster=\"metazen\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "ArgoCD App Sync",
   "type": "logs",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"argocd\"} |~ \"Update successful\" |~ \"$env\""
    }
   ]
  },
  {
   "title": "Pod Restart Total",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, pod) (kube_pod_container_status_restarts_total{cluster=~\"$cluster\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max by (cluster, namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"metazen\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$env.*\"})\n-\nmax by (cluster, namespace, persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=~\"metazen\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$env.*\"}))\n/\nmax by (cluster, namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"metazen\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$env.*\"})*100\n"
    }
   ]
  },
  { "title": "Certificate/Secret/Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Certificate Expiration",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{cluster=~\"$cluster\"} - time()) BY (name,exported_namespace) )",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{cluster=~\"$cluster\"}) BY (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "External Secret Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (externalsecret_status_condition{cluster=~\"$cluster\", condition!=\"Deleted\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Average Log Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count_over_time({cluster=~\"$cluster\",namespace=~\"$env.*\"}[$__range])) by (namespace)"
    }
   ]
  },
  {
   "title": "Error Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", app!~\"zookeeper\", level=~\"error\", namespace=~\"$env.*\" } |~ \"(?i)error\"",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Top 15 Log Publisher",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "topk(15, count_over_time({cluster=~\"$cluster\",namespace=~\"$env.*\"}[$__range]))"
    }
   ]
  }
 ]
}