{{- if .Values.volumeSnapshots }}
{{- range .Values.volumeSnapshots }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    {{- if .labels -}}
    {{ toYaml .labels | nindent 4}}
    {{- end }}
spec:
  volumeSnapshotClassName: {{ $.Values.volumeSnapshotClass.name }}
  source:
    persistentVolumeClaimName: {{ .sourcePvc }}
---
{{- end }}
{{- end }}