apiVersion: v2
appVersion: 0.13.6
version: 6.26.3
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
dependencies:
- name: external-dns
  version: 6.26.3
  repository: https://charts.bitnami.com/bitnami
