argocd:
  namespace: grafana-stack
  releaseName: promtail

promtail:
  nameOverride: promtail
  fullnameOverride: promtail
  kubeNamespace: grafana-stack

  config:
    clients: 
    - url: http://loki-gateway.grafana-stack.svc.cluster.local/loki/api/v1/push ##https://loki-gateway.${ARGOCD_ENV_OPERATOR_DOMAIN}/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
        - docker: {}
        - json:
            expressions:
              level: level
              user_id: user_id
        - labels:
            level:
            user_id:
        - static_labels:
            cluster: ${ARGOCD_ENV_CLUSTER}
            env: ${ARGOCD_ENV_ENVIRONMENT}
            clusterName: eks-${ARGOCD_ENV_NAMESPACE}-${ARGOCD_ENV_ENVIRONMENT}
        # we don't need these label now
        - labeldrop:
            - filename
            - stream
            - job

  tolerations:
    - key: dedicated
      operator: Exists
      effect: NoSchedule
    - key: dedicated
      operator: Exists
      effect: NoExecute

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podLabels:
    cluster: ${ARGOCD_ENV_CLUSTER}
    project: ${ARGOCD_ENV_NAMESPACE}
    env: ${ARGOCD_ENV_ENVIRONMENT}
    tier: infra
    version: 6.15.3

  serviceMonitor:
    enabled: true
    labels: 
      prometheus: ${ARGOCD_ENV_NAMESPACE}
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_cluster]
        action: replace
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_label_project]
        action: replace
        targetLabel: project
      - sourceLabels: [__meta_kubernetes_pod_label_env]
        action: replace
        targetLabel: env