{{- if .Values.serviceMonitor.enabled }}
{{- $serviceMonitor := .Values.serviceMonitor }}
{{- range .Values.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-blackbox-exporter.fullname" $ }}-{{ .name }}
  namespace: {{ template "prometheus-blackbox-exporter.namespace" $ }}
  labels:
    {{- include "prometheus-blackbox-exporter.labels" $ | nindent 4 }}
    {{- if or $serviceMonitor.defaults.labels .labels }}
    {{- toYaml (.labels | default $serviceMonitor.defaults.labels) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: http
    scheme: {{ $serviceMonitor.scheme }}
    {{- if $serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ $serviceMonitor.bearerTokenFile }}
    {{- end }}
    {{- if $serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml $serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    path: "/probe"
    interval: {{ .interval | default $serviceMonitor.defaults.interval }}
    scrapeTimeout: {{ .scrapeTimeout | default $serviceMonitor.defaults.scrapeTimeout }}
    params:
      module:
      - {{ .module | default $serviceMonitor.defaults.module }}
      target:
      - {{ .url }}
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: {{ .url }}
        action: {{ .action }}
      - sourceLabels: [target]
        targetLabel: target
        replacement: {{ .name }}
        action: {{ .action }}
        {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $serviceMonitor.defaults.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel | quote }}
        replacement: {{ $replacement | quote }}
        action: replace
        {{- end }}
    relabelings:
{{- if concat (.additionalRelabeling | default list) $serviceMonitor.defaults.additionalRelabeling }}
{{ toYaml (concat (.additionalRelabeling | default list) $serviceMonitor.defaults.additionalRelabeling) | indent 6 }}
{{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      {{- include "prometheus-blackbox-exporter.selectorLabels" $ | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ template "prometheus-blackbox-exporter.namespace" $ }}
{{- end }}
{{- end }}